defaults:
  - SingleSourceDataPreprocessor@fac.steps.fillnan: FillNaNPreprocessor
  - SingleSourceDataPreprocessor@fac.steps.dtype: DTypePreprocessor

  - SingleSourceDataPreprocessor@ret.steps.dropnan: DropNaNPreprocessor
  - SingleSourceDataPreprocessor@ret.steps.dtype: DTypePreprocessor

  - SingleSourceDataPreprocessor@ret_raw.steps.dropnan: DropNaNPreprocessor
  - SingleSourceDataPreprocessor@ret_raw.steps.dtype: DTypePreprocessor

  - SingleSourceDataPreprocessor@liquidity.steps.fillnan: FillNaNPreprocessor
  - SingleSourceDataPreprocessor@liquidity.steps.dtype: DTypePreprocessor

  - SingleSourceDataPreprocessor@score.steps.fillnan: FillNaNPreprocessor
  - SingleSourceDataPreprocessor@score.steps.dtype: DTypePreprocessor

  - SingleSourceDataPreprocessor@benchmark.steps.fillnan: FillNaNPreprocessor
  - SingleSourceDataPreprocessor@benchmark.steps.dtype: DTypePreprocessor
  
  - SingleSourceDataPreprocessor@bench1.steps.fillnan: FillNaNPreprocessor
  - SingleSourceDataPreprocessor@bench1.steps.dtype: DTypePreprocessor
  - SingleSourceDataPreprocessor@bench2.steps.fillnan: FillNaNPreprocessor
  - SingleSourceDataPreprocessor@bench2.steps.dtype: DTypePreprocessor
  - SingleSourceDataPreprocessor@bench3.steps.fillnan: FillNaNPreprocessor
  - SingleSourceDataPreprocessor@bench3.steps.dtype: DTypePreprocessor
  - SingleSourceDataPreprocessor@bench4.steps.fillnan: FillNaNPreprocessor
  - SingleSourceDataPreprocessor@bench4.steps.dtype: DTypePreprocessor
  - SingleSourceDataPreprocessor@bench5.steps.fillnan: FillNaNPreprocessor
  - SingleSourceDataPreprocessor@bench5.steps.dtype: DTypePreprocessor
  - SingleSourceDataPreprocessor@bench6.steps.fillnan: FillNaNPreprocessor
  - SingleSourceDataPreprocessor@bench6.steps.dtype: DTypePreprocessor
  - _self_

fac:
  _target_: gem.data.SourcePipeline

ret:
  _target_: gem.data.SourcePipeline

ret_raw:
  _target_: gem.data.SourcePipeline

liquidity:
  _target_: gem.data.SourcePipeline

score:
  _target_: gem.data.SourcePipeline

benchmark:
  _target_: gem.data.SourcePipeline

bench1:
  _target_: gem.data.SourcePipeline

bench2:
  _target_: gem.data.SourcePipeline

bench3:
  _target_: gem.data.SourcePipeline

bench4:
  _target_: gem.data.SourcePipeline

bench5:
  _target_: gem.data.SourcePipeline

bench6:
  _target_: gem.data.SourcePipeline