_target_: gem2.data.SourceSpec
name: bench2
format: feather
# path: C:/Users/123/data/feather/benchmark/bench2_20250822.fea
layout: wide
pivot: from_date
date_col: date
code_col: code
value_col: bench2_value
path: /project/model_share_remote/score_file/sub_score/label1/bench2_20250822.fea
