_target_: gem2.data.SourceSpec
name: bench6
format: feather
# path: C:/Users/123/data/feather/benchmark/label1_bench6.fea
layout: wide
pivot: from_date
date_col: date
code_col: code
value_col: bench6_value
path: /project/model_share_remote/score_file/label1_bench6.fea
