_target_: gem2.data.SourceSpec
name: ret
format: feather
# path: C:/Users/123/data/feather/ret/label1.fea
layout: wide
pivot: from_index
index_col: index
date_col: date
code_col: code
value_col: ret_value
path: /project/model_share/share_1/label_data/label1.fea
