_target_: gem.core.data.SourceSpec
name: bench4
format: feather
# path: C:/Users/123/data/feather/benchmark/bench4_20250822.fea
layout: wide
pivot: from_date
date_col: date
code_col: code
value_col: bench4_value
path: /project/model_share_remote/score_file/sub_score/label1/bench4_20250822.fea
