_target_: gem.core.data.SourceSpec
name: benchmark
format: feather
# path: C:/Users/123/data/feather/benchmark/benchmark_1_0819.fea
layout: wide
pivot: from_date
date_col: date
code_col: code
value_col: benchmark_value
path: /project/model_share_remote/score_file/benchmark_1_0819.fea
