_target_: gem.core.data.SourceSpec
name: fac
format: feather
# path: C:/Users/123/data/feather/fac/fac20251017.fea
layout: tabular
date_col: date
code_col: Code
path: /project/model_share/share_1/factor_data/fac20250212/fac20250212.fea
